"""Create the employees table.

Revision ID: 0001_employees
Revises:
Create Date: 2026-09-11

The accounts table: who can sign in, what they may do, and a bcrypt digest of
their password. No plain-text password is stored anywhere in this schema.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0001_employees"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        # The login identifier. Unique and indexed: every sign-in is a lookup
        # on this column, and the index is also what makes a duplicate
        # impossible even if two administrators submit the same ID at once.
        sa.Column("employee_id", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        # bcrypt digest, 60 characters today. Sized for a longer algorithm
        # identifier so a future move to Argon2 is not a schema change.
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False, server_default="EMPLOYEE"),
        sa.Column("department", sa.String(length=80), nullable=False, server_default=""),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint("role IN ('ADMIN', 'EMPLOYEE')", name="ck_employees_role_valid"),
        sa.PrimaryKeyConstraint("id", name="pk_employees"),
    )
    # A single unique index rather than a unique constraint *and* an index:
    # that is what `unique=True, index=True` on the model produces, and two
    # overlapping objects would make every autogenerated migration noisy.
    op.create_index("ix_employees_employee_id", "employees", ["employee_id"], unique=True)


def downgrade() -> None:
    op.drop_index("ix_employees_employee_id", table_name="employees")
    op.drop_table("employees")
